import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../app/components/header/Header";
import Footer from "../app/components/Footer";
import NextTopLoader from "nextjs-toploader"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airnb-clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <NextTopLoader color='#FE595E' />

      {children}</body>
      
    </html>
  );
}
